=== ehasting/GoScope/repo_alternative-3/device.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.scopeportal.com/device"
           xmlns="http://www.scopeportal.com/device.xsd"
           elementFormDefault="qualified">
    <xs:element name="device">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="base">
                    <xs:complexType>
                        <xs:attribute name="id" type="UUID-random" />
                        <xs:attribute name="author" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="version">
                    <xs:complexType>
                        <xs:attribute name="number" type="xs:decimal" />
                        <xs:attribute name="filename" type="xs:string" />
                        <xs:attribute name="added" type="xs:dateTime" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="displayname" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="category" type="xs:string"/>
                <xs:element name="tags">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="site" type="xs:string"/>
                <xs:element name="media" type="media-tag" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="media-tag">
        <xs:sequence>
            <xs:element name="file" type="file-tag" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="file-tag">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" />
                <xs:attribute name="mime" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
     <xs:simpleType name="UUID-random">
        <xs:restriction base="xs:string">
            <xs:length value="36" fixed="true" />
            <xs:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ehasting/GoScope/repo_alternative-3/devices/content of anotherDevice1_0.zip/device.xml
<?xml version="1.0" encoding="UTF-8"?>
<device xmlns="http://www.psy-works.net/device" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.psy-works.net/device device.xsd">
    <base id="8F6476B0-608C-11E2-BCFD-0800200C9A66" author="niceboy"/>
    <version number="1.0" filename="anotherDevice-1.0.zip" added="2013-01-04T09:02:04"/>
    <displayname>Another Device</displayname>
    <description>Mono Transient Shaper</description>
    <category>effects/mono/dynamics</category>
    <tags>
        <tag>Transient Shaper</tag>
        <tag>Dynamics</tag>
    </tags>
    <site>http://forums.planetz.com/viewtopic.php?f=16&amp;t=28778</site>
    <media>
        <file mime="audio/mp3" type="repo-path">/blabla/hey.mp3</file>
        <file mime="image/jpg" type="url">http://www.playboy.com/screenshot.jpg </file>
    </media>
</device>

=== ehasting/GoScope/xml_definitions/device.xml
<?xml version="1.0" encoding="utf-8"?>

<device xmlns="http://www.scope-works.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.scope-works.com device.xsd">
    <base id="anotherdevice" category="Effects/mono/Dynamics" author="niceboy"/>
    <version number="1.0" filename="anotherDevice-1.0.zip" added="2013-01-04T09:02:04" />
    <displayname>Another Device"</displayname>
    <description>Mono Transient Shaper</description>
    <tags>
        <tag>Transient Shaper</tag>
        <tag>Dynamics</tag>
    </tags>
    <site>http://forums.planetz.com/viewtopic.php?f=16&amp;t=28778</site>
    <media>
        <file mime="audio/mp3" type="repo-path">/blabla/hey.mp3</file>
        <file mime="image/jpg" type="url">http://www.playboy.com/screenshot.jpg</file>
    </media>
</device>
